WebMarketAPI/WebMarketMVC/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebMarket.Entities;
using WebMarket.Entities.Models;
using WebMarket.DataAccesLayer.Core.Abstract;
using System.Web.Security;
using WebMarket.Entities.Identity;
using Microsoft.AspNet.Identity;
using System.Drawing;
using System.IO;

namespace WebMarketMVC.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ProductsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Products
        public async Task<ActionResult> Index()
        {
            var products = await _unitOfWork.Products.GetAllAsync();

            return View(products);
        }

        // GET: Products/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await _unitOfWork.Products.GetAsync(id.Value);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public async Task<ActionResult> Create()
        {
            ViewBag.CategoryId = new SelectList(await _unitOfWork.Categories.GetAllAsync(), "Id", "Name");
           
            return View();
        }

        // POST: Products/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Price,ImageURL,CategoryId,SellerId,OrderId")] Product product, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
                return View(product);

            try
            {
                if (file != null)
                {
                    string fileName = Path.GetFileName(file.FileName);
                    string path = Path.Combine(Server.MapPath("~/Content/ProductImages"), fileName);
                    file.SaveAs(path);

                    product.ImageURL = fileName;
                }
                else
                {
                    product.ImageURL = "no-image.png";
                }

                product.SellerId = System.Web.HttpContext.Current.User.Identity.GetUserId();
                _unitOfWork.Products.Add(product);

                await _unitOfWork.Commit();

                var products = await _unitOfWork.Products.GetAllAsync();

                return View("Index", products);
            }
            catch 
            {
                return View("Error");
            }
        }

        // GET: Products/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await _unitOfWork.Products.GetAsync(id.Value);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(await _unitOfWork.Categories.GetAllAsync(), "Id", "Name", product.CategoryId);
           
            return View(product);
        }

        // POST: Products/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Price,ImageURL,CategoryId,SellerId,OrderId")] Product product)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Products.Modify(product);
                await _unitOfWork.Commit();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(await _unitOfWork.Categories.GetAllAsync(), "Id", "Name", product.CategoryId);
           
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await _unitOfWork.Products.GetAsync(id.Value);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Product product = await _unitOfWork.Products.GetAsync(id);
            _unitOfWork.Products.Remove(product);
            await _unitOfWork.Commit();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebMarketAPI/WebMarketMVC/Controllers/UserController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebMarket.DataAccesLayer.Core.Abstract;
using WebMarket.Entities.Identity;
using WebMarket.Entities.Models;

namespace WebMarketMVC.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public UserController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        // GET: User/Index
        public ActionResult Index()
        {
            return RedirectToAction("ShowBasket");
        }

        [HttpGet]
        public async Task<ActionResult> GetOfferedProducts()
        {
            string userId = User.Identity.GetUserId();
            var offeredProducts = await _unitOfWork.Products.GetOfferedProductsOfUserAsync(userId, 0, 10);
            if (offeredProducts == null)
                return HttpNotFound();
            return View(offeredProducts);
        }

        [HttpGet]
        public async Task<ActionResult> GetSoldProducts()
        {
            string userId = User.Identity.GetUserId();
            var soldProducts = await _unitOfWork.Products.GetSoldProductsOfUserAsync(userId, 0, 10);
            if (soldProducts == null)
                return HttpNotFound();
            return View(soldProducts);
        }

        [HttpGet]
        public ActionResult ShowBasket()
        {
            string userId = User.Identity.GetUserId();
            var basketProducts = _unitOfWork.Products.GetProductsFromBasketOfUser(userId, 0, 10);
            if (basketProducts == null)
                return HttpNotFound();
            return View(basketProducts);
        }

        [HttpGet]
        public async Task<ActionResult> AddToBasket(int? productId)
        {
            try
            {
                if (productId == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                var user = await _unitOfWork.Users.GetAsync(User.Identity.GetUserId());
                var product = await _unitOfWork.Products.GetAsync(productId.Value);

                if (product == null)
                    return HttpNotFound();

                if (product.SellerId == user.Id)
                    return View("Error");

                user.Basket.Products.Add(product);
                _unitOfWork.Users.Modify(user);
                await _unitOfWork.Commit();
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
            return RedirectToAction("ShowBasket");
        }

        [HttpGet]
        public async Task<ActionResult> RemoveFromBasket(int? productId)
        {
            try
            {
                if (productId == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                var user = await _unitOfWork.Users.GetAsync(User.Identity.GetUserId());
                var product = await _unitOfWork.Products.GetAsync(productId.Value);
                if (product == null)
                    return HttpNotFound();

                user.Basket.Products.Remove(product);
                _unitOfWork.Users.Modify(user);
                await _unitOfWork.Commit();
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            return RedirectToAction("ShowBasket");
        }



        [HttpGet]
        public async Task<ActionResult> ClearBasket()
        {
            try
            {
                var user = await _unitOfWork.Users.GetAsync(User.Identity.GetUserId());
               
                user.Basket.Products.Clear();
                _unitOfWork.Users.Modify(user);
                await _unitOfWork.Commit();
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            return RedirectToAction("ShowBasket");
        }

        [HttpGet]
        public async Task<ActionResult> GetOrders()
        {
            string userId = User.Identity.GetUserId();
            var orders = await _unitOfWork.Orders.GetOrdersWithProductsOfUserAsync(userId, 0, 10);
            if (orders == null)
                return HttpNotFound();

            return View(orders);

        }

        [HttpGet]
        public async Task<ActionResult> Order()
        {
            try
            {
                var user = await _unitOfWork.Users.GetAsync(User.Identity.GetUserId());

                if (!user.Basket.Products.Any())
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                var orderedProducts = user.Basket.Products.ToArray();

                var order = new Order()
                {
                    BuyerId = user.Id,
                    PurchaseTime = DateTime.Now,
                    Products = orderedProducts
                };
                user.Basket.Products.Clear();
                _unitOfWork.Orders.Add(order);
                await _unitOfWork.Commit();
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
            return RedirectToAction("GetOrders");
        }

    }
}

WebMarketAPI/WebMarketMVC/Views/User/GetOfferedProducts.cshtml
@model IEnumerable<WebMarket.Entities.Models.Product>

 <div class="dashboard">
     <div class="navigation">
         <div class="nav-block">@Html.ActionLink("Panel użytkownika", "Index", "Manage")</div>
         <div class="nav-block">@Html.ActionLink("Sprzedaż", "GetOfferedProducts", "User", new { @class = "active" })</div>
         <div class="nav-block">@Html.ActionLink("Zakupy", "GetOrders", "User")</div>
     </div>

     <div class="data">
         <div style="position: relative">
             <h2>Twoje oferty</h2>
             <a href="/Products/Create" style="position: absolute; right: 0; top: 0"><div class="btn btn-custom">DODAJ OFERTĘ</div></a>
         </div>
         <hr />

         <div class="flex-between">
             <svg class="bi bi-arrow-left-square-fill" width="2em" height="2em" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" cursor="pointer" onclick="PagePrev()">
                 <path fill-rule="evenodd" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.354 10.646a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L6.207 7.5H11a.5.5 0 0 1 0 1H6.207l2.147 2.146z" />
             </svg>

             <h5 id="pages"></h5>

             <svg class="bi bi-arrow-right-square-fill" width="2em" height="2em" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" cursor="pointer" onclick="PageNext()">
                 <path fill-rule="evenodd" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm5.646 10.646a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L9.793 7.5H5a.5.5 0 0 0 0 1h4.793l-2.147 2.146z" />
             </svg>
         </div>

         <hr />

         @foreach (var item in Model)
         {
             <div class="product" category="@item.CategoryId">
                 <div>
                     <img src="~/Content/ProductImages/@item.ImageURL" />
                 </div>

                 <div>
                     <div class="flex-between">
                         <h3>@item.Name</h3>
                         <div>
                             @Html.ActionLink("Edytuj", "Edit", "Products", new { id = item.Id }, new { @class = "btn btn-custom" })
                         </div>
                     </div>
                     <h6>[@item.Category.Name]</h6>
                     <hr />
                     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus sit amet erat quis accumsan. In laoreet, ipsum non sodales laoreet, enim dui tempus tortor, eget bibendum sapien nisl maximus tortor.</p>

                     <div class="prdoduct-buttons">
                         <div class="prdoduct-buttons">
                             <h5>@item.Price zł</h5>
                         </div>
                     </div>
                 </div>
             </div>
         }

         <hr />

         <div class="flex-between">
             <svg class="bi bi-arrow-left-square-fill" width="2em" height="2em" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" cursor="pointer" onclick="PagePrev()">
                 <path fill-rule="evenodd" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.354 10.646a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L6.207 7.5H11a.5.5 0 0 1 0 1H6.207l2.147 2.146z" />
             </svg>

             <h5 id="pages"></h5>

             <svg class="bi bi-arrow-right-square-fill" width="2em" height="2em" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" cursor="pointer" onclick="PageNext()">
                 <path fill-rule="evenodd" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm5.646 10.646a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L9.793 7.5H5a.5.5 0 0 0 0 1h4.793l-2.147 2.146z" />
             </svg>
         </div>

     </div>
 </div>

WebMarketAPI/WebMarketMVC/Views/User/GetOrders.cshtml
@model IEnumerable<WebMarket.Entities.Models.Order>

@{var products = Model.Select(o => o.Products).Distinct();}
<div class="dashboard">
    <div class="navigation">
        <div class="nav-block">@Html.ActionLink("Panel użytkownika", "Index", "Manage")</div>
        <div class="nav-block">@Html.ActionLink("Sprzedaż", "GetOfferedProducts", "User")</div>
        <div class="nav-block">@Html.ActionLink("Zakupy", "GetOrders", "User", new { @class = "active" })</div>
    </div>

    <div class="data">
        <div style="position: relative">
            <h4>Zamówienia</h4>
        </div>

        <hr />

        <div class="flex-between">
            <svg class="bi bi-arrow-left-square-fill" width="2em" height="2em" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" cursor="pointer" onclick="PagePrev()">
                <path fill-rule="evenodd" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.354 10.646a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L6.207 7.5H11a.5.5 0 0 1 0 1H6.207l2.147 2.146z" />
            </svg>

            <h5 id="pages"></h5>

            <svg class="bi bi-arrow-right-square-fill" width="2em" height="2em" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" cursor="pointer" onclick="PageNext()">
                <path fill-rule="evenodd" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm5.646 10.646a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L9.793 7.5H5a.5.5 0 0 0 0 1h4.793l-2.147 2.146z" />
            </svg>
        </div>

        <hr />

        @foreach (var order in Model)
        {
            foreach (var product in order.Products)
            {
                <div class="product" category="@product.CategoryId">
                    <div>
                        <img src="~/Content/ProductImages/@product.ImageURL" />
                    </div>

                    <div>
                        <div class="flex-between">
                            <h3>@product.Name</h3>
                            <h3>@order.PurchaseTime.ToString("yyyy-MM-dd")</h3>
                        </div>
                        <h6>@product.Seller.Email</h6>
                        <hr />
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus sit amet erat quis accumsan. In laoreet, ipsum non sodales laoreet, enim dui tempus tortor, eget bibendum sapien nisl maximus tortor.</p>

                        <div class="prdoduct-buttons">
                            <div class="prdoduct-buttons">
                                <h5>@product.Price zł</h5>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }

        <hr />

        <div class="flex-between">
            <svg class="bi bi-arrow-left-square-fill" width="2em" height="2em" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" cursor="pointer" onclick="PagePrev()">
                <path fill-rule="evenodd" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.354 10.646a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L6.207 7.5H11a.5.5 0 0 1 0 1H6.207l2.147 2.146z" />
            </svg>

            <h5 id="pages"></h5>

            <svg class="bi bi-arrow-right-square-fill" width="2em" height="2em" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" cursor="pointer" onclick="PageNext()">
                <path fill-rule="evenodd" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm5.646 10.646a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L9.793 7.5H5a.5.5 0 0 0 0 1h4.793l-2.147 2.146z" />
            </svg>
        </div>

    </div>
</div>

WebMarketAPI/WebMarketMVC/Views/User/GetSoldProducts.cshtml
@model IEnumerable<WebMarket.Entities.Models.Product>

<h2>Twoje wyprzedane produkty</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Order.BuyerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Seller.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageURL)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Order.BuyerId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Seller.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImageURL)
        </td>
    </tr>
}

</table>

WebMarketAPI/WebMarketMVC/Views/User/Index.cshtml
@model WebMarket.Entities.Identity.User

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<h3>@Model.UserName</h3>

WebMarketAPI/WebMarketMVC/Views/User/ShowBasket.cshtml
@model IEnumerable<WebMarket.Entities.Models.Product>

<div class="center-box">
    <section id="loginForm">
        @if (Model.Count() > 0)
        {
            <h2>Twój koszyk</h2>
            <table class="table">
                <tr>
                    <th>

                    </th>
                    <th>
                        Produkt
                    </th>
                    <th>
                        Cena
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <img src="@Url.Content(item.ImageURL)" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price) zł
                        </td>
                        <td>
                            <a href="/User/RemoveFromBasket?productId=@item.Id" class="btn btn-danger">Usuń</a>
                        </td>
                    </tr>
                }

            </table>

            <div class="flex-between">
                @Html.ActionLink("Wyczyść koszyk", "ClearBasket", null, new { @class = "btn btn-danger" })
                <a href="/User/Order" class="btn btn-custom">Realizuj zamówienie</a>
            </div>
        }
        else
        {
            <h2>Twój koszyk jest pusty</h2>
            <hr/>
            <a href="/" class="btn btn-custom">Zacznij zakupy!</a>
        }
    </section>
</div>